[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "1.0.3"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"


[prune]
  go-tests = true
  unused-packages = true
