[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "1.0.3"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
